apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-expenses-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contoso-expenses-web
  template:
    metadata:
      labels:
        app: contoso-expenses-web
    spec:
      containers:
      - name: contosoexpensesweb
        image: umaracr.azurecr.io/contosoexpensesweb:v1
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: contoso-expenses-web-svc
  labels:
    app: contosoexpenseswebsvc
spec:
  type: ClusterIP
  selector:
    app: contoso-expenses-web
  ports:
  - name: http
    port: 8090
    targetPort: 80
