// <auto-generated />
using Contoso.Expenses.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contoso.Expenses.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200228080225_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contoso.Expenses.API.Models.CostCenter", b =>
                {
                    b.Property<string>("SubmitterEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApproverEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCenterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubmitterEmail");

                    b.ToTable("costCenters");
                });
#pragma warning restore 612, 618
        }
    }
}
